### ISSUE TITLE
Random Daily Drive no longer working console error 400

### ISSUE THREAD

**Issue by donutFred** [Fensterbank/random-daily-drive#20]
Authenticate button works, Generate Playlist doesn't.
In Chrome console I get the error:
                
       DELETE https://api.spotify.com/v1/playlists/6DVxy9FZF0qS7RpTlsIOQm/tracks 400 (Bad Request)

**Comment by Fensterbank** [comment]
Hello,

thanks for your issue and sorry for the late answer. I actually didn't expect anybody using it. 🙂

It seems, the process is failing when we try to empty all the tracks in the already existing playlist.
```typescript
const emptyPlaylist = async (playlistId: string) => {
  const uris = await fetchAllPlaylistTrackUris(playlistId);
  const response = await performRequest(`https://api.spotify.com/v1/playlists/${playlistId}/tracks`, 'DELETE', {
    tracks: uris.map(uri => ({ uri: uri })),
  });
  return response;
}
  ```

I tested it for myself and it's working without issues.
Could you paste me the response from the Spotify API of the failing request using the Devtools?
![grafik](https://github.com/Fensterbank/random-daily-drive/assets/1684826/aa8063a7-178b-4d84-9006-38d6964dae23)

Since it's failing when emptying the existing playlist, you could try these workarounds:
- Delete the playlist "Random Daily Drive" in Spotify manually.
- Use another playlist name in the web app.

In both cases, it would skip that `DELETE` request and should work again.

Still not sure, why it fails at that step, so I would appreciate your input.

**Comment by Fensterbank** [comment]
Since I learned that the app is in fact used by several people on a daily basis, I decided to finally touch the code again, see #22 
My time is limited and I'm soon away in summer vacation, but I have it on my radar now.

**Comment by Fensterbank** [comment]
Found the issue. This happens, if the app tries to remove all tracks from the existing playlist, but it is already empty.
The error is probably a result from a previous failure, where it emptied the playlist but failed to add the tracks.

The issues is now properly handled.
Also released a bunch of improvements.
